epochs: 200
learning-rate: 0.000005
batch-size: 192
num-workers: 8
use-amp: true
use-augment: true
temperature: 0.07

load-checkpoint: false
load-pretrained: true

load-path: "checkpoints/last.pt"
best-path: "checkpoints/best.pt"
last-path: "checkpoints/last.pt"
